experiment:
  name: segmentation_toy_unet

data:
  data_dir: "../datasets/MidTumors"
  batch_size: 8
  num_workers: 2
  cache_rate: 1.0
  target_size: [128, 128]
  val_fraction: 0.1

model:
  type: MiniUNet2D   
  in_channels: 3
  out_channels: 1

training:
  max_epochs: 20
  lr: 0.001
  optimizer: adam
  loss: dice
  val_metric: dice
